// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOesJDxLOXnYXDSbJdtIjkPgvZWi8J5LM',
    appId: '1:477526397574:web:7fc5196be2f16eb73e3707',
    messagingSenderId: '477526397574',
    projectId: 'mytesting2-flutter-project',
    authDomain: 'mytesting2-flutter-project.firebaseapp.com',
    storageBucket: 'mytesting2-flutter-project.appspot.com',
    measurementId: 'G-5S1XQPXXV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZZJGpKqRbbqiOfaUo-al6160ZBCnmCA',
    appId: '1:477526397574:android:505b4719befbe7943e3707',
    messagingSenderId: '477526397574',
    projectId: 'mytesting2-flutter-project',
    storageBucket: 'mytesting2-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8JiXDidVfetcX_OFNTazoK1lv3JVDF4Q',
    appId: '1:477526397574:ios:30c87f602a3200b03e3707',
    messagingSenderId: '477526397574',
    projectId: 'mytesting2-flutter-project',
    storageBucket: 'mytesting2-flutter-project.appspot.com',
    iosClientId: '477526397574-poopaq6os8q7hciq09bmpk25uth9jg1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8JiXDidVfetcX_OFNTazoK1lv3JVDF4Q',
    appId: '1:477526397574:ios:30c87f602a3200b03e3707',
    messagingSenderId: '477526397574',
    projectId: 'mytesting2-flutter-project',
    storageBucket: 'mytesting2-flutter-project.appspot.com',
    iosClientId: '477526397574-poopaq6os8q7hciq09bmpk25uth9jg1l.apps.googleusercontent.com',
    iosBundleId: 'com.example.testingapp',
  );
}
